{{- range $.Values.issuers }}
  {{- if .create }}
    {{- if or (and (.ovhAuthentication) (.ovhAuthenticationRef)) (and (not .ovhAuthentication) (not .ovhAuthenticationRef)) }}
      {{ fail (printf "Invalid issuer %s: For each issuer you wish to create, you need to define either 'ovhAuthentication' or 'ovhAuthenticationRef'" .name) }}
    {{- end }}
    {{- if eq (include "cert-manager-webhook-ovh.isOvhAuthenticationAvail" .) "true" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ printf "%s-ovh-credentials" .name }}
  {{- if eq .kind "Issuer" }}
  namespace: {{ .namespace | quote }}
  {{- else }}
  namespace: {{ $.Release.Namespace | quote }}
  {{- end }}
  labels:
    {{- include "cert-manager-webhook-ovh.labels" $ | nindent 4 }}
data:
  {{- if eq .ovhAuthenticationMethod "application" }}
  applicationKey: {{ .ovhAuthentication.applicationKey | b64enc | quote }}
  applicationSecret: {{ .ovhAuthentication.applicationSecret | b64enc | quote }}
  applicationConsumerKey: {{ .ovhAuthentication.applicationConsumerKey | b64enc | quote }}
  {{- else if eq .ovhAuthenticationMethod "oauth2" }}
  oauth2ClientID: {{ .ovhAuthentication.oauth2ClientID | b64enc | quote }}
  oauth2ClientSecret: {{ .ovhAuthentication.oauth2ClientSecret | b64enc | quote }}
  {{- end }}
---
    {{- end }}{{/* end if eq (include "cert..." */}}
  {{- end }}{{/* end if .create */}}
{{- end }}{{/* end range */}}
